### ISSUE TITLE
Launching the OBF newsletter

### ISSUE THREAD

**Issue by yochannah** [OBF/newsletter#1]
One of the action items from the OBF Birds of Feather meeting was to start releasing a newsletter periodically. I'd suggest we start with OBF related updates as well as community related updates and interesting links. 

This is a call to everyone out there who works in open bioinformatics - please share interesting stuff! This could be a new project launch, an interesting update or release, a link to useful resources (e.g. some nice biology related icons or an open source tool that could be useful, etc. If you aren't sure about something, feel free to drop me a line personally to discuss it, e.g. via [twitter](https://twitter.com/yoyehudi) or email (yochannah@gmail.com).

Promoting yourself or your workplace is _totally_ ok here - this is literally what the newsletter is for, within reason! 

I'll start by leaving a few comments on the issue with possible content items.

**Comment by yochannah** [comment]
Longer newsletter items: 

- GCCBOSC quick summary, including [photos from Berenice Batut](https://www.flickr.com/photos/134305289@N03/sets/72157695693844792/) - if anyone's blogged about their experiences at GCCBOSC, please share on this issue! 
- Logo voting! [Several volunteers have been helping redesign the OBF logo](https://github.com/OBF/obf-docs/issues/43) and we'd like the community to choose which we go with.

**Comment by yochannah** [comment]
Interesting links: (p.s. this is at least partially me promoting stuff I like that I think/hope will be interesting for others, too)

- [PLOS open source toolkit](https://channels.plos.org/open-source-toolkit), a curated set of articles that focuses on good quality open source tools and alternates between hardware and software. Many OBF projects could be highlighted here! 
- [Mozilla Festival, especially the openness space](https://mozillafestival.org/spaces#Openness) - proposals for sessions are open until the end of the month. 
- [Opencon](https://www.opencon2018.org/) - unfortunately applications will close before we get the chance to send this newsletter out, but remote attendance will still be possible.
- [Biology icons from Reactome](https://reactome.org/icon-lib)

**Comment by gedankenstuecke** [comment]
Sorry my connection this morning was terrible, so i might have missed it. But do we plan to have the BOSC survey wrapped up by the time of the newsletter? Otherwise we could share that one again there too.

**Comment by yochannah** [comment]
Ok, quick note: **anyone who wants to share something here that's open bioinformatics-related should feel free to add links to this issue! **

I've started transferring content to a proper draft here: https://docs.google.com/document/d/1-_G3iKcxLNH49hmCsFIqv_IrKy3zqBsyeQ2XA0uLWcQ/edit# - anyone from the OBF board should already have access to edit this, and anyone at all has access to comment. If you'd like access and you don't have it, leave a comment and we'll see what we can do!

**Comment by yochannah** [comment]
I'm not sure about the answer to @gedankenstuecke's question actually. @nlharris are you still looking for input on the GCCBOSC survey or are we happy with the number of answers?

**Comment by lpantano** [comment]
Hi,

don't know how relevant but for miRTop project:

* we have official page for the miRNA annotation format: https://github.com/miRTop/mirGFF3
* we got accepted in FAIRsharing: https://fairsharing.org/bsg-s001218/
* we got a winner for our logo competition: https://github.com/miRTop/mirtop/issues/29#issuecomment-405435689

Feel free to ignore :)

**Comment by yochannah** [comment]
@plants this is exactly the sort of thing we are looking for, thanks!

**Comment by yochannah** [comment]
ok, this issue is frozen accepting any new items and will hopefully go out in the next 24 hours. It has a "if you can't see this email properly" archive version here - https://github.com/OBF/newsletter/blob/master/newsletters/2018-07.md tagging @lpantano and @llrs as your projects are both mentions - if I've made any mistakes, please PR corrections :)

**Comment by yochannah** [comment]
I'll close this once it's emailed out - in the meantime, if anyone wants to propose content for the next issue, please add it here: https://github.com/OBF/newsletter/issues/3
