### ISSUE TITLE
Which licence should we use for the newsletter?

### ISSUE THREAD

**Issue by yochannah** [OBF/newsletter#2]
I was thinking we would create the newsletter using a Google Doc since they're easy for collaborative editing, but then archive the actual newsletter here - perhaps in markdown format? Anyway, it'll need a licence... how do we feel about CC0? Open to other suggestions, too.

**Comment by hlapp** [comment]
Either CC0 or CC-BY. I'm leaning to CC-BY for this, but not strongly so.

**Comment by peterjc** [comment]
I agree with Hilmar, CC0 or CC-BY are the natural choices for the OBF to use here.

 I too lean to the CC-BY for this content as it is the kind of creative writing worth having authorship acknowledged for, and I don't foresee this causing any problems with re-use.

**Comment by yochannah** [comment]
added. Thanks @hlapp @peterjc!

https://github.com/OBF/newsletter/blob/master/LICENCE
