### ISSUE TITLE
Issue 11 of the newsletter

### ISSUE THREAD

**Issue by vdauwera** [OBF/newsletter#24]
This is a call to everyone out there who works in open bioinformatics - please share interesting stuff! This could be a new project launch, an interesting update or release, a link to useful resources (e.g. some nice biology related icons or an open source tool that could be useful, etc. If you aren't sure about something, feel free to drop me a line personally to discuss it, e.g. via twitter ([@VdaGeraldine](https://twitter.com/VdaGeraldine/)) or email ([geraldinevdauwera@gmail.com](mailto:geraldinevdauwera@gmail.com)).

Promoting yourself or your workplace is totally okay here - this is literally what the newsletter is for, within reason!

The aim is to send out this newsletter in March 2023

**Comment by nlharris** [comment]
Newsletter sent--thanks, @vdauwera!

**Comment by vdauwera** [comment]
That was [issue 10 of the newsletter](https://github.com/OBF/newsletter/issues/21), actually — the newsletter process requires opening the next issue / call for input during the development of the then-current issue. Or did I misunderstand something? (I do think we could clarify this in the issue template and update the estimated date of the "next next" newsletter though)

**Comment by nlharris** [comment]
Ohhh sorry, this is for the NEXT newsletter? My bad! I read "The next newsletter will probably be in January 2023" and I thought that "next" meant "not this one".

**Comment by nlharris** [comment]
I suggest changing "The next newsletter will probably be in January 2023" to something like "This aim is to send out this newsletter around January 2023" to help reduce confusion.

**Comment by vdauwera** [comment]
(This is not yet complete)
