### ISSUE TITLE
Issue 12 of the newsletter (May/June 2023)

### ISSUE THREAD

**Issue by vdauwera** [OBF/newsletter#29]
This is a call to everyone out there who works in open bioinformatics - please share interesting stuff! This could be a new project launch, an interesting update or release, a link to useful resources (e.g. some nice biology related icons or an open source tool that could be useful, etc. If you aren't sure about something, feel free to drop me a line personally to discuss it, e.g. via twitter (@VdaGeraldine) or email (geraldinevdauwera@gmail.com).

Promoting yourself or your workplace is totally okay here - this is literally what the newsletter is for, within reason!

The aim is to send out this newsletter around May/June 2023.

**Comment by mr-c** [comment]
Save the date! The CWL 2024 Conference will be the week of May 13th, 2024 in the Netherlands. More details to follow.

**Comment by gedankenstuecke** [comment]
Thanks @mr-c! Added it to the PR!
