### ISSUE TITLE
HTML template for newsletter

### ISSUE THREAD

**Issue by yochannah** [OBF/newsletter#5]
@simran-pandey suggested that we might be able to create a nice HTML template for our newsletters. I'm creating an issue here so we can track any progress. 

Simran and any other interested Outreachy applicants: Please suggest & discuss your ideas here. Feel free to ask me any questions you may have as you're going along. Generally, simpler is better than complex!

**Comment by simran-pandey** [comment]
![image001](https://user-images.githubusercontent.com/31364051/46962192-27831380-d0c0-11e8-9ed6-587776a2c485.png)

Holla everyone! Hope everyone is doing great! :) 

This is a draft layout of the OBF Newsletter that I have created. I have tried incorporating as many relevant elements that would reflect the latest happenings at OBF in a crisp and concise manner for the email newsletter  :)

I started by creating a basic layout having placeholders and added digital notes alongside. 

- Newsletter may start with an opening message from an OBF member followed by 

- two articles in spotlight -- a small brief/summary of the article, Photo and name of authors and a read more button which will open to the full 2-4 page article pdf

- Highlights from OBF( or in collaboration with OBF) events and links to watch the event (linking to YouTube), read the highlight ( media coverage articles, newspaper clippings etc.), read more about the event - linking to website of the program

- More sections can be added(or removed) as per the need

- Followed by the social media handles and website link

Your feedback and suggestions are welcomed on the same :D

**Comment by jamessandy** [comment]
Hello guys am on this😉😉😉

**Comment by jamessandy** [comment]
Hey guys, I did a little pencil and Paper mock up this and Will be done with it soon 
![img_20181101_192210](https://user-images.githubusercontent.com/33603488/47871512-907ec100-de0c-11e8-920e-40da52aa1819.jpg)

**Comment by simran-pandey** [comment]
Hey @yochannah I just made a pull request after making the CSS inline and changed the overall theme to OBF colors. There's just one index file now with much shorter and concise code, additionally there's one images folder having all the placeholder images :)

You can also find the files here -- https://github.com/simran-pandey/newsletter/tree/master/OBF%20Newsletter%20-%20V1

**Comment by yochannah** [comment]
Closing this issue for now - we can revisit later if needed.
